######################## default configuration ####################
baseURL = "/"
title = "Breathe Life"
theme = "omega"
# google analytics
googleAnalytics = "" # example : UA-123-45
[markup.goldmark.renderer]
unsafe= true

######################### navigation ##############################


[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1

[[menu.main]]
name = "About"
pre = ""
url = "about"
weight = 2

[[menu.main]]
name = "Get Involved Today"
pre = ""
url = "goal"
weight = 3

[[menu.main]]
name = "testimonials"
pre = ""
url = "testimonials"
weight = 4

[[menu.main]]
name = "Contact us"
pre = ""
url = "contact"
weight = 6



#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = ""
menu = "GIVE"
menu_url = "give"

# Meta data
description = "breathe life"
author = "Themefisher"
# contact info
contact_info = "1001 Brickell bay <br>Dr. Miami, <br>FL 33131"
# Preloader
preloader = true
# google map
[params.map]
enable = true
gmap_api = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7946.308513203729!2d100.48114753448746!3d5.238450000000008!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ab79101eb5f1f%3A0xdf352d232f26eba7!2sHong%20Lun%20Sdn%20Bhd!5e0!3m2!1sen!2smy!4v1646904951212!5m2!1sen!2smy"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
map_marker = "images/map-marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

[params.contact]
phone= '+6017 413 0454'
email="info@breathelife.org.my"
text= "We welcome your involvement in the support of our refugee families; Finances are crucial in serving them well.<br><br>Trained midwives/doulas, educators (any level) and social workers can contact us via email to volunteer services."
image = "/images/contact/1.png"

[[params.aaa]]
title = 'Security'
url= "/security"
[[params.aaa]]
title = 'Privacy'
url= "/privacy"
[[params.aaa]]
title = 'Term of Use'
url= "/tnc"

[params.footer]
title = 'Copyright Â© BREATHE LIFE 202201014862 (1460559-H)<br>Website managed by <img src="/images/shinajii.svg">. <br>All rights reserved.'
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fa-facebook" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "#"

[[params.social]]
title = "instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "#"

[[params.social]]
title = "twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "#"

